### ISSUE TITLE
运行不成功~

### ISSUE THREAD

**Issue by juehackr** [kakajun/memory-number-training#1]
![Uploading 微信截图_20240904171732.png…]()

**Comment by juehackr** [comment]
![微信截图_20240904171732](https://github.com/user-attachments/assets/0b7ac254-5daa-4ee3-ab7a-c54a3bd6cc26)

**Comment by kakajun** [comment]
先排除是不是node版本问题吧, 我的是node 20, gh-pages 都能够运行打包成功哦, 
![image](https://github.com/user-attachments/assets/955a5eb4-b088-408a-a519-2a449025fa87)
